name:                haskellbook
version:             0.1.0.0
github:              "evenbrenden/haskellbook"
license:             BSD3
author:              "Even Brenden"
maintainer:          "evenbrenden@gmail.com"
copyright:           "2019 Even Brenden"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         haskellbook.com

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  - src/ch8
  - src/ch11
  - src/ch14
  - src/ch15
  - src/ch23
  - src/ch24
  - src/cipher
  exposed-modules:
  - Lib
  - E8
  - E11
  - Fool
  - MonoidSemigroupHelpers
  - Optional
  - WriteStateForYourself
  - Cipher
  - ParsingConfigurationFiles
  dependencies:
  - time
  - QuickCheck
  - checkers
  - scotty
  - uuid
  - text
  # - hgrev
  - optparse-applicative
  - aeson
  - network
  - random
  - bytestring
  - hedis
  - network-uri
  - trifecta
  - integer-logarithms
  - containers
  - raw-strings-qq
  - hspec
  - transformers
  - directory
  - vector

executables:
  haskellbook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbook

tests:
  haskellbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbook
    - hspec
    - hspec-discover
    - QuickCheck
